### ISSUE TITLE
Should I use the source-forge plugin or your fork?

### ISSUE THREAD

**Issue by giamma** [ljader/redmine-mylyn-plugin#5]
Hi, 

I am currently using the source forge hosted Eclipse plug-in for Redmine in conjunction with this https://github.com/danmunn/redmine_mylyn_connector connector.

I noticed that you are maintaining your fork of both the Eclipse and the Redmine plug-ins.

What is the state of your work? Do you recommend using your code?

Thanks
Giamma.

**Comment by ljader** [comment]
I'm closing this issue, because:
* [README.md](https://github.com/ljader/redmine-mylyn-plugin/blob/master/README.md) has been updated with installation instructions (that both redmine connector and eclipse plugin are requires, how to get and install Eclipse plugin, how to develop plugin).
* [GitHub Releases](https://github.com/ljader/redmine-mylyn-plugin/releases/latest) contains ZIP with P2 repo for latest version (currently 0.4.0) of the plugin.

Please check that out!
