### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by devbau** [ljader/redmine-mylyn-plugin#68]
Please can you provide proper installation instructions?

How exactly it should be installed?

**Comment by ljader** [comment]
[README.md](https://github.com/ljader/redmine-mylyn-plugin/blob/master/README.md) has been updated with installation - please check that out

**Comment by awilkins** [comment]
TBH ljader, a lot of the problems people are having are with the different transitive dependencies of the various different Eclipse editions - does the single build the CI server provides cover this issue? I myself always check out the sources and build the update-site for my specific Eclipse edition with Maven, because the feeling that I will have dependency issues otherwise has not left me.

**Comment by ljader** [comment]
@awilkins I think all Eclipse plugins are affected from various Eclipse versions and its not uncommon to have different builds / update sites for different Eclipse versions:
http://www.eclipse.org/ajdt/downloads/
http://projects.eclipse.org/projects/modeling.sirius/downloads
http://wiki.eclipse.org/Stardust/Download

So I think there are 2 solutions:
- refactor code to be universal across different Eclipse versions - this will result with one P2 repo
- create different P2 repos for different Eclipse version

Many of recorded issues in GitHub was about unable to resolve one of 3 dependencies:
- org.json_1.0.0
- org.aspectj.runtime_1.7.3
- org.eclipse.equinox.log_1.2.300

The first 2 are currently bundled with this plugins P2 repo, but the third one is not.
My idea is to remove references to this plugin from plugin code and rely only on standard Eclipse plugin logging mechanism.

What do you think about it?
